services:
    #App Server
    laravel-docker-app:
        container_name: laravel-pneumatika
        build: .
        volumes:
            - /pneumatika:/var/www/html
        ports:
            - "8000:80"

    #Database
    mysql_db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pneumatika
        ports:
            - "3306:3306"
    #phpMyAdmin Server
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql_db
            PMA_PORT: 3306
